services:
  # =====================================
  # 1) POSTGRES CHO AIRFLOW (metadata DB)
  # =====================================
  airflow-postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pg_data:/var/lib/postgresql/data

  # =====================================
  # 2) AIRFLOW WEBSERVER
  # =====================================
  airflow-webserver:
    image: apache/airflow:2.7.3
    env_file:
      - ./.env
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "duckdb pandas"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./duckdb:/opt/airflow/duckdb
    ports:
      - "8080:8080"
    command: webserver

  # =====================================
  # 3) AIRFLOW SCHEDULER
  # =====================================
  airflow-scheduler:
    image: apache/airflow:2.7.3
    env_file:
      - ./.env    
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "duckdb pandas"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./duckdb:/opt/airflow/duckdb
    command: scheduler

  # =====================================
  # 4) AIRFLOW INIT (chạy 1 lần duy nhất)
  # =====================================
  airflow-init:
    image: apache/airflow:2.7.3
    container_name: airflow_init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./duckdb:/opt/airflow/duckdb
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --role Admin --firstname admin --lastname admin --email admin@example.com"

volumes:
  airflow_pg_data:

